font_family           RobotoMono Nerd Font
bold_font             auto
italic_font           auto
bold_italic_font      auto
shell /bin/zsh

background_opacity    0.7
background            #400869
foreground            #28c5d4
selection_foreground  #7a1eb0
selection_background  #7a1eb0
cursor                #1ba1ab
