[main]
# General layout and sizing
font=RobotoMono Nerd Font:size=12
lines=10
width=40
horizontal-pad=20
vertical-pad=20
inner-pad=10

# Behavior
terminal=kitty # Set your preferred terminal
prompt=-> 
layer=overlay

[colors]
background=1a0324ff
text=eb21e4ff
match=f38ba8ff
selection=bb1be3ff
selection-text=3b0523ff
border=7013d4ff

[border]
width=2
radius=8
